doctrine:
    orm:
        mappings:
            TpayPaymentModule:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../modules/tpay/src/Entity"
                prefix: Tpay\Entity
                alias: Tpay
