name: Pull request

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json, fileinfo
          coverage: none

      - run: composer install --no-dev -o

      - run: git archive --output=tpay-prestashop.zip HEAD --prefix=tpay/

      - run: mkdir tpay && mv vendor tpay/
      - run: zip -ur tpay-prestashop.zip tpay/
      - run: zip -d tpay-prestashop.zip "tpay/_dev/*" || true
      - run: zip -d tpay-prestashop.zip "tpay/.github/*" || true
      - run: zip -d tpay-prestashop.zip "tpay/.php*" || true
      - run: zip -d tpay-prestashop.zip "tpay/.gitignore" || true

      - name: Build marketplace zip
        run: |
          cp tpay-prestashop.zip tpay-prestashop-marketplace.zip
          mkdir -p marketplace_patch/tpay
          unzip -j tpay-prestashop.zip "tpay/tpay.php" -d marketplace_patch/tpay/
          sed -i "s/define('_TPAY_MARKETPLACE_RELEASE', false)/define('_TPAY_MARKETPLACE_RELEASE', true)/" marketplace_patch/tpay/tpay.php
          cd marketplace_patch && zip -u ../tpay-prestashop-marketplace.zip tpay/tpay.php

      - run: mkdir plugin-standalone && unzip tpay-prestashop.zip -d plugin-standalone
      - run: mkdir plugin-marketplace && unzip tpay-prestashop-marketplace.zip -d plugin-marketplace

      - uses: actions/upload-artifact@v4
        id: upload-standalone
        with:
          name: 'tpay-prestashop'
          path: 'plugin-standalone/'
          include-hidden-files: true

      - uses: actions/upload-artifact@v4
        id: upload-marketplace
        with:
          name: 'tpay-prestashop-marketplace'
          path: 'plugin-marketplace/'
          include-hidden-files: true

      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Tpay Prestashop plugin
            - Standalone: ${{ steps.upload-standalone.outputs.artifact-url }}
            - Marketplace: ${{ steps.upload-marketplace.outputs.artifact-url }}
