name: Static code analysis

on: [push]

jobs:
  # Check that there are no syntax errors in the project
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax checker
        uses: prestashop/github-action-php-lint/${{ matrix.php }}@master

  # Check that the PHP code follows the coding standards
#  php-cs-fixer:
#    name: PHP-CS-Fixer
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2.0.0
#
#      - name: Run PHP-CS-Fixer
#        uses: prestashopcorp/github-action-php-cs-fixer@master

  # Run PHPStan against the module and a PrestaShop release
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - presta-version: '1.7.7.8'
            experimental: true

          - presta-version: '1.7.8.11'
            experimental: true

          - presta-version: '8.1.7'
            experimental: false

          - presta-version: '8.2.6'
            experimental: false

          - presta-version: '9.0.3'
            experimental: true

          - presta-version: '9.1.3'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      # Add vendor folder in cache to make next builds faster
      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      # Add composer local folder in cache to make next builds faster
      - name: Cache composer folder
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install --no-interaction --prefer-dist

      # Docker images prestashop/prestashop may be used, even if the shop remains uninstalled
      - name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:${{ matrix.presta-versions }}

      # Run a container for PHPStan, having access to the module content and PrestaShop sources.
      # This tool is outside the composer.json because of the compatibility with PHP 5.6
      - name : Run PHPStan (Tag ${{ matrix.presta-versions }})
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module ghcr.io/devgine/composer-php:v2-php8.2-alpine php vendor/bin/phpstan analyse --configuration=tests/phpstan/phpstan.neon --memory-limit=1G

